### ISSUE TITLE
Compiling protoc-gen-twirp_ruby plugin

### ISSUE THREAD

**Issue by skatkov** [arthurnn/twirp-ruby#113]
Has anyone ever tried to distribute protoc-gen-twirp_ruby plugin in a compiled form? Maybe even through brew or just binaries?

The fact, that we need to have go locally is a bit of nuance for us.

go install github.com/twitchtv/twirp-ruby/protoc-gen-twirp_ruby

**Comment by skatkov** [comment]
I managed to get this compiled and published via Github Releases.

https://github.com/skatkov/protoc-gen-twirp-ruby

This compiled version could later be easily used by protoc as a plugin, via --plugin argument.

if you are interested, I'm happy to bring this to this repository.

**Comment by arthurnn** [comment]
@skatkov ultimately, having to maintain also a go toolchain here is not ideal for many reasons:
- releasing to two package managers
- version mismatches
- extra install and moving pieces

Now, if we also need to compile and distribute the plugin, is yet another piece in the release process.
Although I am not discarding this option, I would favor we doing a ruby protoc port, such as [this](https://github.com/arthurnn/twirp-ruby/issues/123)

**Comment by skatkov** [comment]
@arthurnn indeed, having a Ruby-based plugin that generates standardrb compliant ruby code sounds like a way better solution.
