### ISSUE TITLE
Open to new maintainers?

### ISSUE THREAD

**Issue by danielmorrison** [arthurnn/twirp-ruby#114]
@arthurnn are you open to others helping maintain this gem? My team has been using this gem heavily across multiple projects and would be happy to help. We have a couple PRs that have been open for many months without any movement. Happy to help share the load, with no intention of making breaking changes. 

/cc @gaffneyc @darronschall

**Comment by gaffneyc** [comment]
@arthurnn Raising this again because I'd be interested in helping maintain twirp-ruby. We've been using it for years and have quite a few things depending on it.

**Comment by arthurnn** [comment]
Hi everyone, so sorry for my late reply. 
Yes, we would love help maintaining this library. We heavily use it at GitHub too. 
I will put a reminder on my calendar when I am back from vacation , second week of Jan, and I will organize myself so we can make an intro. For the time being, if you have proposals, PRs, issues, create them away, and we can review them together in the new year. 

thanks

**Comment by glogiotatidis** [comment]
👋 Hey folks, can you please share the outcome of your discussions? We (@Shopify) are interested in using this library and we are curious about the current status of the project and its maintenance. We are open to explore options to support the ongoing work.

**Comment by arthurnn** [comment]
👋  We use this library at GitHub, and there is a low amount of maintenance needed. We are also trying to put a few folks together to officialy maintain the project. 
@glogiotatidis feel free to open issues/PRs here, and I will try to review them, if you folks need any improvements.

**Comment by arthurnn** [comment]
I will be closing this, as the outcome is: Feel free to open PRs/Issues and I will review them at least once a week.

**Comment by danielmorrison** [comment]
@arthurnn I appreciate the renewed commitment. At @collectiveidea, we use this pretty heavily. 

I poke at our two outstanding issues.

#97 was originally part of a PR that broke some other things, but is now it is clean. It is a blocker and causes us to hand-fix files a lot. 

#105 is pretty straightforward. 

Our team (including @gaffneyc, @darronschall, and me) are happy to help and we'll start poking and cleaning up PRs.
