### ISSUE TITLE
Please publish the 1.11.0 version to Rubygems

### ISSUE THREAD

**Issue by fidalgo** [arthurnn/twirp-ruby#120]
The latest version, 1.11.0 is not published on rubygems: https://rubygems.org/gems/twirp/versions/

Can you please upload it?

**Comment by fidalgo** [comment]
@darronschall You're right, I was misled by the tags:
https://github.com/arthurnn/twirp-ruby/blob/v1.10.0/twirp.gemspec
https://github.com/arthurnn/twirp-ruby/blob/v1.11.0/twirp.gemspec

So my request would be to release the version v1.11.0, as the current v1.10.0 is not usable at all, because there's a missing `rack` dependency.

This is the fix we need: https://github.com/arthurnn/twirp-ruby/blob/v1.11.0/twirp.gemspec#L24C1-L24C71

Would it be possible to release a new version, to cover it?

**Comment by fidalgo** [comment]
@darronschall  Here is the commit that fixed the problem: https://github.com/arthurnn/twirp-ruby/commit/aa4000f8ea9ff84447060ab8a7f425ed70e0bf56

There's also another use complaining about the same problem and asking for a release that would include that commit.

**Comment by darronschall** [comment]
@fidalgo Unfortunately, I can't help you further as I'm not a maintainer of this gem (see #114).

You can set up your Gemfile to use the `main` branch, though, instead of waiting for a new release:

```ruby
gem "twirp", github: "arthurnn/twirp-ruby"
```

**Comment by fidalgo** [comment]
Thank you for your reply, unfortunately this is a dependency of a gem, so I cannot use that github syntax.
I will for now stick the version to the previous working version and maybe this will catch @arthurnn 's attention.

**Comment by chrisbloom7** [comment]
Would also be great if we could get the`google-protobuf` dependency bumped/relaxed as well

https://github.com/arthurnn/twirp-ruby/blob/v1.11.0/twirp.gemspec#L22

google-protobuf v3.25 has a bug that prevents it from building properly on certain linux distros. The gem then jumps from 3.25 directly to 4.26, but the current dependency specifier in the gemspec prevents us from upgrading.

**Comment by arthurnn** [comment]
> Would also be great if we could get thegoogle-protobuf dependency bumped/relaxed as well

done: https://github.com/arthurnn/twirp-ruby/pull/122

**Comment by arthurnn** [comment]
https://rubygems.org/gems/twirp/versions/1.12.0 release with latest.

see [here](https://github.com/arthurnn/twirp-ruby/blob/main/RELEASE_NOTES.md#1110---not-released) why 1.11.0 was not release to rubygems.
